config/routes.rb
SimpleLogin::Application.routes.draw do
  get 'comments/create'

  get 'posts/create'

  root 'users#new'
  resources :users
  resources :sessions, :only => [:new, :create, :destroy] #only need 3 restful routes for Sessions

  get "/index"  => 'users#new'
  get "/signout" => 'sessions#destroy'
  get "/signin" => 'users#new'
 
  post "/posts" => 'posts#create'
  post "/comments" => 'comments#create'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	# Relationships
	belongs_to :user
	belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	# Relationship
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Relationships
  has_many :post

  #this allows my form to contain a password field and use it on the model side, even though there is no field
  #in my database called password (we used encrypted_password)
  attr_accessor :password, :password_confirmation

  email_regex = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i

  validates :first_name,    :presence   => true,
            :length               => { :maximum => 30 }

  validates :last_name,    :presence   => true,
            :length               => { :maximum => 30 }

  validates :email,   :presence   => true,
            :format               => { :with => email_regex },
            :uniqueness           => { :case_sensitive => false }
            #this validates the form input
  validates :password,  :presence => true,
            :confirmation         => true,
            :length               => { :within => 4..100 }

  #before the user gets added to DB, run this function.
  before_save :encrypt_password

  #this method encrypts the user's unencrypted login attempt and returns true if the password is a match
  def has_password?(submitted_password)
    self.encrypted_password == encrypt(submitted_password)
  end

  # class method that checks whether the user's email and submitted password are valid
  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil if user.nil?
    return user if user.has_password?(submitted_password)
  end

  private
    def encrypt_password
      # generate a unique salt if it's a new user
      # self.password uses the attr_accessor we defined above to allow me to grab the inputed password 
      self.salt = Digest::SHA2.hexdigest("#{Time.now.utc}--#{self.password}") if self.new_record?
    
      # encrypt the password and store that in the encrypted_password field
      self.encrypted_password = encrypt(self.password)  #this self.password is what's in the post data!
    end

    # encrypt the password using both the salt and the passed password
    def encrypt(pass)
      Digest::SHA2.hexdigest("#{self.salt}--#{pass}")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  #allow all controllers to have access to the sessions helper
  include SessionsHelper
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
	@data = Comment.create(:user_id => comment_params[:user_id], :post_id => comment_params[:post_id], :comment => comment_params[:comment] )
	redirect_to "/users/#{comment_params[:user_id]}"
  end

  private
    def comment_params
    	params.require(:comment).permit(:user_id, :post_id, :comment)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
  	@post = Post.create( :user_id => post_params[:user_id], :message => post_params[:message])
  	redirect_to "/users/#{post_params[:user_id]}";
  end

  def post_params
    params.require(:post).permit(:user_id, :message)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  #bring up a form for a new session aka login form
  def new
    
  end

  #create the session resource ie, let user log in
  def create
    #this references the funciton we made in user.rb
  	user = User.authenticate(params[:session][:email], params[:session][:password])
  	if user.nil?
  		flash[:error_login] = "couldn't find a user with those credentials"
      #if there is an error, redirect back to login
      redirect_to '/'
  	else
  		sign_in user #helper function
  		redirect_to user
  	end
  end

  def destroy
  	sign_out #helper function 
  	redirect_to signin_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new #form to make new user
    @user = User.new
  end

  def create #restful route to make new user!
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      flash[:notice] = 'New user created!'
      redirect_to @user
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_path
    end
  end

  def show
    @user = User.find(params[:id])
    @posts = Post.joins(:user).all.order('created_at DESC')
    @comments = Comment.includes(:post).includes(:user).order('created_at DESC')
  end
  
  #define strong parameters!
  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
    #set the value of the current user, IE use the method below
    self.current_user=(user)
  end
  
  # setter method, set the value of the current user as an instance variable!
  def current_user=(user)
    @current_user = user
  end

  # getter method, returns info of current user
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  #if there is a current user, IE someone is logged in, this function returns TRUE!
  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session[:user_id] = nil
    #resets the current user to nil using the current_user= setter method
    self.current_user = nil
  end

  #this function returns true if the user I pass to the function is equal the current user signed in
  def current_user?(user)
    user == self.current_user 
  end

  def deny_access
    redirect_to signin_path, :notice => "Please sign in to access this page."
  end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SimpleLogin</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>User#index</h1>
<p>Find me in app/views/user/index.html.erb</p>

app/views/users/new.html.erb
<!-- Login and Registration -->
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="/assets/stylesheets/user.css.scss">
</head>
<body>
	<div id="wrapper">
		<div id="header">
			<h2>The Wall</h2>
		</div>
		<div id="main_container">
			<div id="register">
				<h3>Register</h3>
				<% if flash[:errors] %>
					<% flash[:errors].each do |error| %>
						<p><%= error %></p>
					<% end %>
				<% end %>
				<%= simple_form_for(@user) do |f| %>
				  <%= f.input :first_name %>
				  <%= f.input :last_name %>
				  <%= f.input :email %>
				  <%= f.input :password %>
				  <%= f.input :password_confirmation %>
				  <%= f.button :submit, "Register" %>
				<% end %>
			</div>
		
			<div id="login">
				<h3>Login</h3>
				<% if flash[:error_login] %>
					<p><%= flash[:error_login] %></p>
				<% end %>
				<%= simple_form_for(:session, :url => sessions_path) do |f| %>
				  <%= f.input :email %>
				  <%= f.input :password %>
				  <%= f.button :submit, "Login"%>
				<% end %>
			</div>
		</div>	
	</div>
</body>
</html>

app/views/users/show.html.erb
<!-- Wall Page -->
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
	<link rel="stylesheet" href="/assets/stylesheets/user.css.scss">
</head>
<body>
	<div id="wrapper">
		<div id="header">
			<h2>The Wall</h2>
			<div id="user_panel">
				<h3><%= @user.first_name %> | <%= link_to('Log off', signout_path) %></h3>	
			</div>
		</div>
		<div id="main_container">
			<h3>Post a message</h3>
			<%= simple_form_for :post, :url => "/posts" do |f| %>
			 	<%= f.input :message , :as => :text, label: false, :input_html => {:cols => 96, :rows => 5}%>
				<%= f.hidden_field :user_id, :value => "#{@user.id.to_s}" %>
			 	<%= f.button :submit, "Post a message", :class => 'submit_button' %>
			<% end %>
			<div class="clear"></div>
			<% @posts.each do |post| %>
				<div id="post_container">
					<h4><%= post.user.first_name %> - <%= Date.strptime(post.user.created_at.to_s).strftime("%b %d, %Y") %></h4>
					<p><%= post.message %></p>
					
					<% @comments.each do |comment| %>
						<% if comment.post_id == post.id %>
							<div class="comment_container">
								<h4><%= comment.user.first_name %> - <%= Date.strptime(comment.user.created_at.to_s).strftime("%b %d, %Y") %></h4>
								<p><%= comment.comment %></p>
							</div>
						<% end %>
					<% end %>
					<div id="comment_area">
						<%= simple_form_for :comment, :url => "/comments" do |f| %>
						 	<%= f.input :comment, :as => :text, label: false, :input_html => {:cols => 91}%>
							<%= f.hidden_field :post_id, :value => "#{post.id.to_s}" %>
							<%= f.hidden_field :user_id, :value => "#{@user.id.to_s}" %>
						 	<%= f.button :submit, "Post a Comment", :class => 'submit_button' %>
						<% end %>
					</div>
					<div class="clear"></div>					
				</div>
			<% end %>
		</div>
	</div>
</body>
</html>